export class InterestList {
    list = [
        'Bioinformatics',
        'Biostatistics',
        'Cancer Biology',
        'Clinical Pathology',
        'Comparative Genomics',
        'Comparative Medicine',
        'Computational Biology',
        'Computational Chemistry',
        'Developmental Endocrinology',
        'Developmental Toxicology',
        'Electrophysiology',
        'Endocrine Disruptors',
        'Endocrinology',
        'Environmental Epidemiology',
        'Environmental Genetics',
        'Environmental Genomics',
        'Enzymology',
        'Epigenetics',
        'Experimental Pathology',
        'Female Reproduction',
        'Genetic Epidemiology',
        'Genetics / Nucleic Acid',
        'Genomics',
        'Immunogenetics',
        'Infectious Diseases',
        'Laboratory Animal Science',
        'Male Reproduction',
        'Medicinal Chemistry',
        'Molecular Epidemiology',
        'Molecular Pathogenesis',
        'Nanotechnology',
        'Neurobiology',
        'Neuroimmunology',
        'Neuropathology',
        'Neuropharmacology',
        'Nutrition',
        'Oncology',
        'Pathology',
        'Pediatric Epidemiology',
        'Pharmacogenetics',
        'Photobiology',
        'Preventive Medicine',
        'Public Health',
        'Renal Physiology',
        'Reproductive Biology',
        'Reproductive Epidemiology',
        'Reproductive Toxicology',
        'Respiratory Physiology',
        'Respiratory Toxicology',
        'Signal Transduction',
        'Structural Biology',
        'Surgery',
        'Systems Biology',
        'Toxicogenetics',
        'Toxicogenomics',
        'Translational Research',
        'Veterinary Medicine',
        "Women's Health",
        'Comparative Pathobiology',
        'Acute Lung Injury',
        'ADHD',
        'Agricultural Workers Diseases',
        'Alcoholism',
        'Allergy',
        "Alzheimer's Disease",
        "Amyotrophic Lateral Sclerosis (ALS)",
        'Asthma',
        'Autism',
        'Autoimmune Diseases',
        'Birth Defects',
        'Bladder Diseases / Cancer',
        'Breast Cancer',
        'Cancer',
        'Cardiac Arrhythmias',
        'Cardiovascular Diseases',
        'Child Development',
        'Cognitive Function / Delay',
        'Deafness',
        'Developmental Disabilities / Delay',
        'Diabetes',
        'Endometriosis',
        'Environmental Lung Diseases',
        'Epilepsy',
        'Facial Clefts',
        'Fertility / Infertility',
        'Hepatic Failure',
        'HIV / AIDS',
        'Hypothyroidism',
        'Kidney Diseases',
        'Lactation',
        'Leukemia',
        'Liver Diseases / Cancer',
        'Low Birthweight',
        'Lung Diseases / Cancer',
        'Menopause',
        'Menstruation / Menstrual Cycle',
        'Mitochondrial Diseases',
        'Mortality, Infant / Neonatal',
        'Neurobehavioral Diseases',
        'Neurodegenerative Diseases',
        'Neurodevelopmental Diseases',
        'Obesity',
        'Ovulation / Conception',
        "Parkinson's Disease",
        'Polycystic Ovary Syndrome (PCOS)',
        'Pre-Eclampsia',
        'Pregnancy',
        'Prostate Diseases / Cancer',
        'Psychomotor Function / Delay',
        'Puberty',
        'Pulmonary Fibrosis',
        'Pulmonary Heart Disease',
        'Pulmonary Infections',
        'Respiration Disorders',
        'Stress',
        'Systemic Lupus Erythematosus / SLE',
        'Uterine Fibroids / Leiomyoma',
        'Applied Mathematics',
        'Biochemistry',
        'Biophysics',
        'Cell / Molecular Biology',
        'Chemistry',
        'Computer Sciences',
        'Developmental Biology',
        'Ecology',
        'Education',
        'Engineering',
        'Epidemiology',
        'Genetics',
        'Geology',
        'Geophysics',
        'Immunology',
        'Mathematics',
        'Medical Sciences',
        'Microbiology',
        'Neuroscience',
        'Pharmacology',
        'Physics',
        'Physiology',
        'Plant Biology',
        'Psychology',
        'Public Health',
        'Social Sciences',
        'Statistics',
        'Toxicology',
        'Bank mergers',
        'Bankruptcy',
        'Big box stores',
        'Brand awareness',
        'Competitive intelligence',
        'Consumer loyalty',
        'Consumer risk',
        'Copycat products',
        'Corporate crime',
        'Corporate culture',
        'Corporate social responsibility',
        'Customer competencies',
        'Data security',
        'Employee coaching',
        'Franchises',
        'Green products',
        'Industry disruptor',
        'Intellectual capital',
        'Job sculpting',
        'Marketing ethics',
        'Mergers',
        'Organigraphs',
        'Outsourcing',
        'Philanthropy',
        'Quality circles',
        'Regional planning',
        'Risk management',
        'Service initiatives',
        'Shared services model',
        'Short-term financing',
        'Starbucks Effect',
        'Strategic planning',
        'Strikes',
        'Subliminal advertising',
        'Telemarketing',
        'Underage workers',
        'Underwriting',
        'Undocumented workers',
        'Unions',
        'Whistle blowing',
        'Work ethic',
        'Work-life balance',
        'Workplace diversity',
        'Bias in promotions',
        'Core competencies',
        'Dress code',
        'Downsizing',
        'Employee benefit planning',
        'Employment equity',
        'Flexible scheduling',
        'Glass ceiling',
        'Harassment',
        'Human resources',
        'Knowledge management',
        'Labor disputes',
        'Mentoring',
        'Public unions',
        'Reverse performance evaluation',
        'Sexual harassment',
        'Strategic human resource management',
        'Succession management',
        'Team leadership',
        'Telecommuting',
        'Total quality management',
        'Trans Pacific Partnership',
        'Troubled employees',
        'Workplace atmosphere',
        'Workplace dating',
        'Workplace violence',
        'Austerity measures',
        'Bailout',
        'Bitcoin',
        'Coinage',
        'Consumerism',
        'Credit Crisis',
        'Currency manipulation',
        'Cyber Monday',
        'Demonitisation',
        'Depression',
        'Econometrics',
        'Economic stimulus approaches',
        'Exchange rates',
        'Farm subsidies',
        'Federal interest rates',
        'Flash crashes',
        'Flat taxes',
        'Forecasting',
        'Foreign exchange',
        'Great Recession',
        'Green economy',
        'Housing market crash',
        'Informal economy',
        'Interest rates',
        'Minimum wage',
        'National debt',
        'Prevailing wage laws',
        'Recession',
        'Sharing economy',
        'Shop local',
        'Tariffs',
        'Unemployment',
        'United Kingdom leaving EU',
        'Venezuela economic collapse',
        'World economy',
    ]
}